name: Test 2
on:
  push:
    branches:
      - migrate-pipelines
    paths-ignore: [ 'README.md' ]
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        shell: powershell
        run: |
          docker run -t mcr.microsoft.com/windows/servercore:ltsc2019 powershell -command "echo hello"