name: Tests
on:
  push:
    branches:
      - master
      - migrate-pipelines
    paths-ignore: [ 'README.md' ]

  workflow_dispatch:
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass
          docker build -t hwc-test .
          docker run --rm -it hwc-test:latest