name: Tests
on:
  push:
    branches:
      - master
      - migrate-pipelines
    paths-ignore: [ 'README.md' ]

  workflow_dispatch:
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/windows-container
        name: Run Windows Tests
        id: windows-test