name: Tests
on:
  push:
    branches:
      - master
      - migrate-pipelines
    paths-ignore: [ 'README.md' ]

  workflow_dispatch:
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Run Tests
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass
          docker rmi mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
          docker rmi mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
          docker rmi mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
          docker rmi mcr.microsoft.com/windows/nanoserver:1809
          docker rmi mcr.microsoft.com/windows/servercore:ltsc2019
          docker build -t hwc-test .
          docker run hwc-test:latest