name: Tests
on:
  push:
    branches:
      - master
      - migrate-pipelines
    paths-ignore: [ 'README.md' ]

  workflow_dispatch:
jobs:
  test-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test go version before
        run: |
          go version
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '^1'
      - name: Test go version after
        run: |
          go version